package com.ftn.sbnz.kjar.templates;
import com.ftn.sbnz.model.domain.*;

rule "Drug-Disease Interaction: ANTICOAGULANT + renal insufficiency - row 0"
when
    $req : MedicationRequest(
        $patient : patient,
        $newMed : newMedication,
        newMedication.category == MedicationCategory.ANTICOAGULANT
    )
    eval($patient.hasDiagnosis("renal insufficiency"))
then
    insert(new DetectedInteraction(
        $patient,
        null,
        $newMed,
        InteractionType.DRUG_DISEASE,
        SeverityLevel.SERIOUS,
        SeverityLevel.SERIOUS.getScore(),
        "Impaired kidney function slows drug excretion increasing bleeding risk"
    ));
end

rule "Drug-Disease Interaction: ANTIDIABETIC + renal insufficiency - row 1"
when
    $req : MedicationRequest(
        $patient : patient,
        $newMed : newMedication,
        newMedication.category == MedicationCategory.ANTIDIABETIC
    )
    eval($patient.hasDiagnosis("renal insufficiency"))
then
    insert(new DetectedInteraction(
        $patient,
        null,
        $newMed,
        InteractionType.DRUG_DISEASE,
        SeverityLevel.CONTRAINDICATED,
        SeverityLevel.CONTRAINDICATED.getScore(),
        "Drug accumulation leads to hypoglycemia risk"
    ));
end

rule "Drug-Disease Interaction: STATIN + liver disease - row 2"
when
    $req : MedicationRequest(
        $patient : patient,
        $newMed : newMedication,
        newMedication.category == MedicationCategory.STATIN
    )
    eval($patient.hasDiagnosis("liver disease"))
then
    insert(new DetectedInteraction(
        $patient,
        null,
        $newMed,
        InteractionType.DRUG_DISEASE,
        SeverityLevel.CONTRAINDICATED,
        SeverityLevel.CONTRAINDICATED.getScore(),
        "Statins metabolized in liver, damaged liver causes toxicity"
    ));
end

rule "Drug-Disease Interaction: ANTICOAGULANT + liver disease - row 3"
when
    $req : MedicationRequest(
        $patient : patient,
        $newMed : newMedication,
        newMedication.category == MedicationCategory.ANTICOAGULANT
    )
    eval($patient.hasDiagnosis("liver disease"))
then
    insert(new DetectedInteraction(
        $patient,
        null,
        $newMed,
        InteractionType.DRUG_DISEASE,
        SeverityLevel.SERIOUS,
        SeverityLevel.SERIOUS.getScore(),
        "Damaged liver combined with anticoagulant drastically increases bleeding risk"
    ));
end


